# Generated by Django 6.0.6 on 2026-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='known',
            field=models.BooleanField(default=False),
        ),
    ]
