# Generated by Django 6.0.6 on 2026-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0002_word_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='known',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
