# Generated by Django 6.0.6 on 2026-06-28 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0003_alter_word_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='next_review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
